name: Continuous Integration

on:
  push:
  pull_request:
  workflow_dispatch:
    name: Build only (iOS)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build-only-ios:
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET 8.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Install .NET Workloads
        run: dotnet workload install maui-ios

      - name: Build
        run: dotnet build -c Debug osu.iOS
